var load_funcs=[],unload_funcs=[],useragent=navigator.userAgent,isios=/(iPad|iPhone|iPod)/.test(useragent),isandroid=/Android/.test(useragent),ismobile=isios||isandroid||/Mobile/.test(useragent);isios&&document.writeln('<link href="/images/css/ios.css" rel="stylesheet" type="text/css" media="all">');function register_onload_handler(a){load_funcs.push(a)}function register_onunload_handler(a){unload_funcs.push(a)}
function body_onload(){rollover_setup();if(document.getElementsByTagName){for(var a=document.getElementsByTagName("a"),b=0;b<a.length;++b){var c=a[b];c.getAttribute("href")&&"ext"==c.getAttribute("rel")&&(c.target="_blank")}for(b=0;b<load_funcs.length;++b)load_funcs[b]()}}function body_onunload(){for(var a=0;a<unload_funcs.length;++a)unload_funcs[a]()}var imghash=[];
function rollover_setup(){for(var a=document.getElementsByTagName("img"),b=0;b<a.length;++b){var c=a[b],d=c.id;if(d&&"rollover_"==d.substring(0,9)){var e=c.src.lastIndexOf(".");imghash[d+"_h"]=new Image;imghash[d+"_h"].src=c.src.substring(0,e)+"_h"+c.src.substring(e,c.src.length);imghash[d+"_n"]=new Image;imghash[d+"_n"].src=c.src;c.onmouseover=rollover_on;c.onmouseout=rollover_off}}}function rollover_on(){this.src=imghash[this.id+"_h"].src}
function rollover_off(){this.src=imghash[this.id+"_n"].src}function toggle_div(a){a&&(a=document.getElementById(a))&&(a.style.display="block");for(a=1;a<toggle_div.arguments.length;++a){var b=toggle_div.arguments[a];b&&(b=document.getElementById(b))&&(b.style.display="none")}return!1}function fmask_needed(){return navigator&&navigator.appName&&-1!=navigator.appName.indexOf("Microsoft")&&navigator.appVersion&&7>parseInt(navigator.appVersion)}var popup_fmask;
function fmask_show(a,b){if(fmask_needed()){popup_fmask||(popup_fmask=document.createElement("iframe"),popup_fmask.style.position="absolute",popup_fmask.style.border="none",popup_fmask.style.visibility="hidden","https:"==location.protocol&&(popup_fmask.src="/blank.html"));var c=a.parentNode||document.getElementsByTagName("body")[0];c&&(c.appendChild(popup_fmask),popup_fmask.style.width=a.offsetWidth+"px",popup_fmask.style.height=a.offsetHeight+"px",popup_fmask.style.top=a.style.top?a.style.top:a.offsetTop?
a.offsetTop+"px":"",popup_fmask.style.left=a.style.left?a.style.left:a.offsetLeft?a.offsetLeft+"px":"",popup_fmask.style.zIndex=b||(a.style.zIndex?a.style.zIndex-1:1),popup_fmask.style.visibility="visible")}}function fmask_hide(){popup_fmask&&(popup_fmask.style.visibility="hidden",popup_fmask.parentNode&&popup_fmask.parentNode.removeChild(popup_fmask))}var shown_popup_id;
function popup_show(a,b,c){if(b=document.getElementById(a))return shown_popup_id&&popup_hide(shown_popup_id),b.style.display="block",shown_popup_id=a,fmask_show(b),!1}function popup_hide(a){fmask_hide();document.getElementById(a).style.display="none";shown_popup_id=null;return!1}var dprint_enabled;function dprint_enable(){dprint_enabled=!0}function dprint_disable(){dprint_enabled=!1}
function dprint(a){if(dprint_enabled)if("undefined"!==typeof console)console.log(a);else{var b=document.getElementById("logframe");b||(b=document.createElement("div"),b.className="logframe",b.style.position="absolute",b.id="logframe",document.body.appendChild(b));b.insertBefore(document.createElement("br"),b.firstChild);b.insertBefore(document.createTextNode(a),b.firstChild)}}var zoom_active;
function zoom_hide(){if(zoom_active)return fmask_hide(),document.body.removeChild(zoom_active),zoom_active=!1}
function zoom_show(){zoom_active&&zoom_hide();var a=document.body,b=document.createElement("div");b.className="zoomed";var c=document.createElement("div");c.className="inner";var d=document.createElement("div");d.className="close";var e=document.createElement("a");e.href="#";e.onclick=zoom_hide;e.appendChild(document.createTextNode("Close"));d.appendChild(e);var f=new Image;f.src=this.zsrc;c.appendChild(f);c.appendChild(d);b.appendChild(c);b.onclick=e.onclick;b.title="Click to close";b.style.zIndex=
99;zoom_active=b;c=b.offsetWidth;if(!c||c<this.zwidth+40)c=this.zwidth+40;b.style.top=(document.body.parentNode.scrollTop||0)+100+"px";b.style.left=(1E3<c?50:Math.floor((1E3-c)/2))+"px";a.insertBefore(b,a.firstChild);fmask_show(b);return!1}
function zoom_setup(){for(var a=document.getElementsByTagName("img"),b=0;b<a.length;++b){for(var c=a[b],d=c.className.split(" "),e=!1,f=0;f<d.length;++f)if("zoom"==d[f].substr(0,4)&&!isNaN(parseInt(d[f].substr(4)))){e=parseInt(d[f].substr(4));break}e&&(d=c.src,f=d.search(/-\d+\.\w+$/),0>f||(d=d.substr(0,f+1)+e+d.substr(d.indexOf(".",f)),c.zwidth=e,c.zsrc=d,c.style.cursor="pointer",c.onclick=zoom_show))}}var pageTracker;function urchinTracker(a){pageTracker&&pageTracker._trackPageview(a)}
function httpReqNew(){var a;window.XMLHttpRequest?a=new XMLHttpRequest:window.ActiveXObject&&(a=new ActiveXObject("Msxml2.XMLHTTP"));return a}function httpReqGet(a,b,c,d){try{a||(a=httpReqNew()),a&&(a.onreadystatechange=function(){c(a)},a.open("GET",b,!0),a.send(null))}catch(e){d&&d(e.message,e)}};
